version: '3'
name: git-hub_actions
services:
  git-hub_actions:
    container_name: git-hub_actions
    image: al1fe/git-hub_actions
    restart: always
    ports:
      - "7443:443"
      # - "7080:80"
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production # Development
      - ASPNETCORE_URLS=https://+:443 # ;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$ASPNETCORE_Kestrel__Certificates__Default__Password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./aspnetapp02.pfx
    volumes:
      - ./aspnetapp02.pfx:/app/aspnetapp02.pfx
      - ./etc/ssl/:/etc/nginx/ssl/
