version: '3'
name: GitHubActions
services:
  bot:
    container_name: git-hub_actions
    image: al1fe/git-hub_actions
    restart: always
    ports:
      - "7777:80"
    environment:
      ENVIRONMENT: Production
