version: '3'
name: git-hub_actions
services:
  git-hub_actions:
    container_name: git-hub_actions
    image: al1fe/git-hub_actions
    restart: always
    ports:
      - "7080:80"
      - "7443:443"
