name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: BackEnd
      run: |
        docker build . --file Dockerfile -t al1fe/git-hub_actions
        docker images
        
    - name: Save Docker image as tarball
      run: |
        docker save al1fe/git-hub_actions -o git-hub_actions.tar
        
    - name: SSH into server, down containers and delete image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker stop git-hub_actions || true  # Остановка текущего контейнера, если он запущен
          docker rm git-hub_actions || true  # Удаление предыдущего контейнера, если он существует
          docker load -i git-hub_actions.tar  # Загрузка образа из tarball
          docker run -d --name git-hub_actions -p 7777:5203 al1fe/git-hub_actions  # Запуск контейнера
    