name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: BackEnd
      run: |
        docker build . --file Dockerfile -t al1fe/git-hub_actions
        docker images
        
    - name: Save Docker image as tarball
      run: |
        docker save al1fe/git-hub_actions -o git-hub_actions.tar
      # env:
        # DOCKER_IMAGE_TARBALL: git-hub_actions.tar
        
    - name: copy image to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "git-hub_actions.tar"
        target: "~/"        
          
    - name: SSH into server, down containers and delete image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker load -i ~/git-hub_actions.tar
          docker run -d --name git-hub_actions -p 7777:5203 al1fe/git-hub_actions