name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: BackEnd
      run: |
        docker build . --file Dockerfile -t al1fe/GitHubActions
        docker images
        
    - name: Save Docker image as tarball
      run: |
        docker save al1fe/GitHubActions -o GitHubActions.tar
    