name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: BackEnd
      run: |
        docker build . --file Dockerfile -t al1fe/GitHubActions
        docker images
        
    - name: Save Docker image as tarball
      run: |
        docker save al1fe/GitHubActions -o GitHubActions.tar

    uses: appleboy/ssh-action@master
    with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
      run: |      
        docker stop GitHubActions || true  # Остановка текущего контейнера, если он запущен
        docker rm GitHubActions || true  # Удаление предыдущего контейнера, если он существует
        docker load -i GitHubActions.tar  # Загрузка образа из tarball
        docker run -d --name GitHubActions -p 7777:5203 al1fe/GitHubActions  # Запуск контейнера

      
      
      
        # ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'docker stop GitHubActions || true'  # Остановка текущего контейнера, если он запущен
        # ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'docker rm GitHubActions || true'  # Удаление предыдущего контейнера, если он существует
        # ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'docker load -i GitHubActions.tar'  # Загрузка образа из tarball
        # ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'docker run -d --name GitHubActions -p 7777:5203 al1fe/GitHubActions'  # Запуск контейнера

    - name: Clean up
      run: |
        rm eng-bot.tar
      
      # run: |        
        # docker build -t al1fe/eng-bot -f TelegramEngBot/Dockerfile .
      
        # if ! docker image inspect al1fe/tacotron2-model; then
          # docker build -t al1fe/tacotron2-model -f ../Tacotron2/Dockerfile .
        # fi
        
    # - name: SSH into server, down containers and delete image
      # uses: appleboy/ssh-action@master
      # with:
        # host: ${{ secrets.SERVER_HOST }}
        # port: ${{ secrets.SERVER_PORT }}
        # username: ${{ secrets.SERVER_USERNAME }}
        # password: ${{ secrets.SERVER_PASSWORD }}
        # script: |
          # ls -la

          
          # docker compose pull
          # docker compose up        
          # docker compose down
          # docker image rm al1fe/eng-bot
          # docker compose pull
          # docker compose up
